version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: samuelamin/dockerized-laravel-11
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    user: www-data

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER:  ${DB_USERNAME}
      MYSQL_PASSWORD:  ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  mysql-data:
