services:
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/letsencrypt
      - .:/var/www
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - laravel-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew && sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: user_password
    ports:
      - "8073:80"
    networks:
      - laravel-network

networks:
  laravel-network:
